
var CanvasKitInit = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  return (
function(CanvasKitInit) {
  CanvasKitInit = CanvasKitInit || {};

var e;e||(e=typeof CanvasKitInit !== 'undefined' ? CanvasKitInit : {});
(function(a){a.gd=a.gd||[];a.gd.push(function(){a.MakeCanvasSurface=function(b){var c=document.getElementById(b);if(!c)throw"Canvas with id "+b+" was not found";if(b=this._getRasterN32PremulSurface(c.width,c.height))b.yc=c,b.kd=c.width,b.hd=c.height,b.jd=b.kd*b.hd*4,b.Xc=a._malloc(b.jd);return b};a.MakeSurface=function(b,c){var d=this._getRasterN32PremulSurface(b,c);d&&(d.yc=null,d.kd=b,d.hd=c,d.jd=b*c*4,d.Xc=a._malloc(d.jd));return d};a.SkSurface.prototype.flush=function(){this._flush();if(this.yc)if(this._readPixels(this.kd,
this.hd,this.Xc)){var b=new Uint8ClampedArray(a.buffer,this.Xc,this.jd);b=new ImageData(b,this.kd,this.hd);this.yc.getContext("2d").putImageData(b,0,0)}else console.wc("could not read pixels")};a.SkSurface.prototype.dispose=function(){this.Xc&&a._free(this.Xc);this.delete()};a.currentContext=function(){};a.setCurrentContext=function(){}})})(e);(function(a){function b(a){return Math.round(Math.max(0,Math.min(a||0,255)))}a.Color=function(a,d,f,g){return b(255*g)<<24|b(a)<<16|b(d)<<8|b(f)<<0}})(e);
(function(a){function b(b,c){if(!b||!b.length)return d;var f=a._malloc(b.length*c.BYTES_PER_ELEMENT);c.set(b,f/c.BYTES_PER_ELEMENT);return f}function c(b,c){if(!b||!b.length)return d;for(var f=a._malloc(b.length*b[0].length*c.BYTES_PER_ELEMENT),g=0,m=f/c.BYTES_PER_ELEMENT,l=0;l<b.length;l++)for(var q=0;q<b[0].length;q++)c[m+g]=b[l][q],g++;return f}a.onRuntimeInitialized=function(){a.SkPath.prototype.addPath=function(){if(1===arguments.length)this._addPath(arguments[0],1,0,0,0,1,0,0,0,1);else if(2===
arguments.length)this._addPath(arguments[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7]||0,a[8]||0,a[9]||1);else if(7===arguments.length||10===arguments.length){var a=arguments;this._addPath(arguments[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7]||0,a[8]||0,a[9]||1)}else return console.wc("addPath expected to take 1, 2, 7, or 10 args. Got "+arguments.length),null;return this};a.SkPath.prototype.arc=function(a,b,c,d,m,l){this._arc(a,b,c,d,m,!!l);return this};a.SkPath.prototype.arcTo=function(a,b,c,d,m){this._arcTo(a,
b,c,d,m);return this};a.SkPath.prototype.close=function(){this._close();return this};a.SkPath.prototype.conicTo=function(a,b,c,d,m){this._conicTo(a,b,c,d,m);return this};a.SkPath.prototype.cubicTo=function(a,b,c,d,m,l){this._cubicTo(a,b,c,d,m,l);return this};a.SkPath.prototype.dash=function(a,b,c){return this._dash(a,b,c)?this:null};a.SkPath.prototype.lineTo=function(a,b){this._lineTo(a,b);return this};a.SkPath.prototype.moveTo=function(a,b){this._moveTo(a,b);return this};a.SkPath.prototype.op=function(a,
b){return this._op(a,b)?this:null};a.SkPath.prototype.quadTo=function(a,b,c,d){this._quadTo(a,b,c,d);return this};a.SkPath.prototype.simplify=function(){return this._simplify()?this:null};a.SkPath.prototype.stroke=function(b){b=b||{};b.width=b.width||1;b.miter_limit=b.miter_limit||4;b.cap=b.cap||a.yg.ye;b.join=b.join||a.zg.xg;return this._stroke(b)?this:null};a.SkPath.prototype.transform=function(){if(1===arguments.length){var a=arguments[0];this._transform(a[0],a[1],a[2],a[3],a[4],a[5],a[6]||0,a[7]||
0,a[8]||1)}else if(6===arguments.length||9===arguments.length)a=arguments,this._transform(a[0],a[1],a[2],a[3],a[4],a[5],a[6]||0,a[7]||0,a[8]||1);else throw"transform expected to take 1 or 9 arguments. Got "+arguments.length;return this};a.SkPath.prototype.trim=function(a,b,c){return this._trim(a,b,!!c)?this:null};a.SkVertices.prototype.applyBones=function(b){var c=a.HEAPF32;if(b&&b.length&&b[0].length){for(var f=a._malloc(b.length*b[0].length*b[0][0].length*c.BYTES_PER_ELEMENT),k=0,m=f/c.BYTES_PER_ELEMENT,
l=0;l<b.length;l++)for(var q=0;q<b[0].length;q++)for(var v=0;v<b[0][0].length;v++)c[m+k]=b[l][q][v],k++;c=f}else c=d;b=this._applyBones(c,b.length);a._free(c);return b};a.SkImage.prototype.encodeToData=function(){if(0===arguments.length)return this._encodeToData();if(2===arguments.length){var a=arguments;return this._encodeToDataWithFormat(a[0],a[1])}throw Error("encodeToData expected to take 0 or 2 arguments. Got "+arguments.length);};a.gd&&a.gd.forEach(function(a){a()})};a.LTRBRect=function(a,b,
c,d){return{fLeft:a,fTop:b,fRight:c,fBottom:d}};var d=0;a.MakeSkDashPathEffect=function(c,d){d||(d=0);if(!c.length||1===c.length%2)throw"Intervals array must have even length";var f=b(c,a.HEAPF32);c=a._MakeSkDashPathEffect(f,c.length,d);a._free(f);return c};a.MakeImageShader=function(b,c,d){var f=a._malloc(b.byteLength);a.HEAPU8.set(new Uint8Array(b),f);return a._MakeImageShader(f,b.byteLength,c,d)};a.MakeLinearGradientShader=function(c,d,h,k,m,l,q){var f=b(h,a.HEAP32);k=b(k,a.HEAPF32);q=q||0;l?(6===
l.length&&l.push(0,0,1),c=a._MakeLinearGradientShader(c,d,f,k,h.length,m,q,l)):c=a._MakeLinearGradientShader(c,d,f,k,h.length,m,q);a._free(f);a._free(k);return c};a.MakeRadialGradientShader=function(c,d,h,k,m,l,q){var f=b(h,a.HEAP32);k=b(k,a.HEAPF32);q=q||0;l?(6===l.length&&l.push(0,0,1),c=a._MakeRadialGradientShader(c,d,f,k,h.length,m,q,l)):c=a._MakeRadialGradientShader(c,d,f,k,h.length,m,q);a._free(f);a._free(k);return c};a.MakeSkVertices=function(d,g,h,k,m,l,q){var f=c(g,a.HEAPF32);h=c(h,a.HEAPF32);
k=b(k,a.HEAP32);m=c(m,a.HEAP32);l=c(l,a.HEAPF32);var K=b(q,a.HEAPU16);d=a._MakeSkVertices(d,g.length,f,h,k,m,l,q&&q.length||0,K);f&&a._free(f);h&&a._free(h);k&&a._free(k);K&&a._free(K);m&&a._free(m);l&&a._free(l);return d};a.MakeNimaActor=function(b,c){var d=a._malloc(b.byteLength);a.HEAPU8.set(new Uint8Array(b),d);var f=a._malloc(c.byteLength);a.HEAPU8.set(new Uint8Array(c),f);return a._MakeNimaActor(d,b.byteLength,f,c.byteLength)}})(e);
(function(a){function b(b){this.Pd=b;this.ae=new c(b.getCanvas());this.getContext=function(a){return"2d"===a?this.ae:null};this.toDataURL=function(){this.Pd.flush();var b=this.Pd.makeImageSnapshot();if(b){if(b=b.encodeToData())return b=a.getSkDataBytes(b),"data:image/png;base64,"+btoa(String.fromCharCode.apply(null,b));console.error("encoding failure")}else console.error("no snapshot")}}function c(b){this.yc=b;this.Lc=new a.SkPaint;this.Lc.setAntiAlias(!0);this.Kc=null;this.td=!1;Object.defineProperty(this,
"font",{enumerable:!0,set:function(){this.Lc.setTextSize(30)}});Object.defineProperty(this,"strokeStyle",{enumerable:!0,set:function(){}});this.beginPath=function(){this.Kc&&this.Kc.delete();this.Kc=new a.SkPath;this.td=!1};this.Od=function(a,b){this.Kc||this.beginPath();return this.td?!0:(this.td=!0,this.moveTo(a,b),!1)};this.fillText=function(a,b,c){this.yc.drawText(a,b,c,this.Lc)};this.lineTo=function(a,b){this.Od(a,b)&&this.Kc.lineTo(a,b)};this.measureText=function(a){return{width:this.Lc.measureText(a)}};
this.moveTo=function(a,b){this.Od(a,b)&&this.Kc.moveTo(a,b)};this.rotate=function(a,b,c){this.yc.rotate(180*a/Math.PI,b||0,c||0)};this.scale=function(a,b){this.yc.scale(a,b)};this.setTransform=function(a,b,c,d,m,l){this.yc.setMatrix([a,c,m,b,d,l,0,0,1])};this.skew=function(a,b){this.yc.skew(a,b)};this.stroke=function(){this.Kc&&(this.Lc.setStyle(a.PaintStyle.$d),this.yc.drawPath(this.Kc,this.Lc))};this.strokeText=function(b,c,d){this.Lc.setStyle(a.PaintStyle.$d);this.yc.drawText(b,c,d,this.Lc)};this.translate=
function(a,b){this.yc.translate(a,b)}}a.MakeCanvas=function(c,f){a.initFonts();return(c=a.MakeSurface(c,f))?new b(c):null}})(e);var aa={},n;for(n in e)e.hasOwnProperty(n)&&(aa[n]=e[n]);e.arguments=[];e.thisProgram="./this.program";e.quit=function(a,b){throw b;};e.preRun=[];e.postRun=[];var ba=!1,ca=!1,ea=!1,fa=!1;ba="object"===typeof window;ca="function"===typeof importScripts;ea="object"===typeof process&&"function"===typeof require&&!ba&&!ca;fa=!ba&&!ea&&!ca;var p="";
function ha(a){return e.locateFile?e.locateFile(a,p):p+a}
if(ea){p=__dirname+"/";var ia,ja;e.read=function(a,b){ia||(ia=require("fs"));ja||(ja=require("path"));a=ja.normalize(a);a=ia.readFileSync(a);return b?a:a.toString()};e.readBinary=function(a){a=e.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(e.thisProgram=process.argv[1].replace(/\\/g,"/"));e.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ka))throw a;});process.on("unhandledRejection",r);e.quit=function(a){process.exit(a)};
e.inspect=function(){return"[Emscripten Module object]"}}else if(fa)"undefined"!=typeof read&&(e.read=function(a){return read(a)}),e.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?e.arguments=scriptArgs:"undefined"!=typeof arguments&&(e.arguments=arguments),"function"===typeof quit&&(e.quit=function(a){quit(a)});else if(ba||ca)ca?p=self.location.href:document.currentScript&&
(p=document.currentScript.src),_scriptDir&&(p=_scriptDir),0!==p.indexOf("blob:")?p=p.substr(0,p.lastIndexOf("/")+1):p="",e.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ca&&(e.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),e.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||
0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},e.setWindowTitle=function(a){document.title=a};var la=e.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),t=e.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||la);for(n in aa)aa.hasOwnProperty(n)&&(e[n]=aa[n]);aa=void 0;function ma(a){var b=u;u=u+a+15&-16;return b}
function na(a){var b=w[x>>2];a=b+a+15&-16;w[x>>2]=a;return a>=y&&!oa()?(w[x>>2]=b,0):b}function pa(a){var b;b||(b=16);return Math.ceil(a/b)*b}var qa={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},ra=[],sa=!1;function assert(a,b){a||r("Assertion failed: "+b)}
function ta(a){var b;if(0===b||!a)return"";for(var c=0,d,f=0;;){d=z[a+f>>0];c|=d;if(0==d&&!b)break;f++;if(b&&f==b)break}b||(b=f);d="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,z.subarray(a,a+Math.min(b,1024))),d=d?d+c:c,a+=1024,b-=1024;return d}return ua(z,a)}var va="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ua(a,b){for(var c=b;a[c];)++c;if(16<c-b&&a.subarray&&va)return va.decode(a.subarray(b,c));for(c="";;){var d=a[b++];if(!d)return c;if(d&128){var f=a[b++]&63;if(192==(d&224))c+=String.fromCharCode((d&31)<<6|f);else{var g=a[b++]&63;if(224==(d&240))d=(d&15)<<12|f<<6|g;else{var h=a[b++]&63;if(240==(d&248))d=(d&7)<<18|f<<12|g<<6|h;else{var k=a[b++]&63;if(248==(d&252))d=(d&3)<<24|f<<18|g<<12|h<<6|k;else{var m=a[b++]&63;d=(d&1)<<30|f<<24|g<<18|h<<12|k<<6|m}}}65536>d?c+=String.fromCharCode(d):(d-=
65536,c+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else c+=String.fromCharCode(d)}}
function wa(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var k=a.charCodeAt(++g);h=65536+((h&1023)<<10)|k&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(2097151>=h){if(c+3>=d)break;b[c++]=240|h>>18}else{if(67108863>=h){if(c+4>=d)break;b[c++]=248|h>>24}else{if(c+5>=d)break;b[c++]=252|h>>30;b[c++]=128|h>>24&63}b[c++]=128|h>>18&63}b[c++]=
128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}function xa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:2097151>=d?b+4:67108863>=d?b+5:b+6}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");var ya=65536,za=16777216,Aa=16777216;function Ba(a,b){0<a%b&&(a+=b-a%b);return a}var buffer,A,z,Ca,Da,w,B,Ea,Fa;
function Ga(){e.HEAP8=A=new Int8Array(buffer);e.HEAP16=Ca=new Int16Array(buffer);e.HEAP32=w=new Int32Array(buffer);e.HEAPU8=z=new Uint8Array(buffer);e.HEAPU16=Da=new Uint16Array(buffer);e.HEAPU32=B=new Uint32Array(buffer);e.HEAPF32=Ea=new Float32Array(buffer);e.HEAPF64=Fa=new Float64Array(buffer)}var Ha,u,Ia,Ja,Ka,La,Ma,x;Ha=u=Ja=Ka=La=Ma=x=0;Ia=!1;e.reallocBuffer||(e.reallocBuffer=function(a){try{var b=A;var c=new ArrayBuffer(a);(new Int8Array(c)).set(b)}catch(d){return!1}return Na(c)?c:!1});
function oa(){var a=e.usingWasm?ya:za,b=2147483648-a;if(w[x>>2]>b)return!1;var c=y;for(y=Math.max(y,Aa);y<w[x>>2];)536870912>=y?y=Ba(2*y,a):y=Math.min(Ba((3*y+2147483648)/4,a),b);a=e.reallocBuffer(y);if(!a||a.byteLength!=y)return y=c,!1;e.buffer=buffer=a;Ga();return!0}var Oa;try{Oa=Function.prototype.call.bind(Object.getOwnPropertyDescriptor(ArrayBuffer.prototype,"byteLength").get),Oa(new ArrayBuffer(4))}catch(a){Oa=function(b){return b.byteLength}}
var Pa=e.TOTAL_STACK||5242880,y=e.TOTAL_MEMORY||33554432;y<Pa&&t("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+y+"! (TOTAL_STACK="+Pa+")");e.buffer?buffer=e.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(e.wasmMemory=new WebAssembly.Memory({initial:y/ya}),buffer=e.wasmMemory.buffer):buffer=new ArrayBuffer(y),e.buffer=buffer);Ga();
function Qa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.wd;"number"===typeof c?void 0===b.vd?e.dynCall_v(c):e.dynCall_vi(c,b.vd):c(void 0===b.vd?null:b.vd)}}}var Ra=[],Sa=[],Ta=[],Ua=[],Va=[],Wa=!1;function Xa(){var a=e.preRun.shift();Ra.unshift(a)}var Ya=Math.trunc,Za=0,$a=null,ab=null;e.preloadedImages={};e.preloadedAudios={};
function bb(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(e.wasmBinary)return new Uint8Array(e.wasmBinary);if(e.readBinary)return e.readBinary(f);throw"both async and sync fetching of the wasm failed";}catch(q){r(q)}}function b(){return e.wasmBinary||!ba&&!ca||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+"'";return a.arrayBuffer()}).catch(function(){return a()})}function c(a){function c(a){k=a.exports;
if(k.memory){a=k.memory;var b=e.buffer;a.byteLength<b.byteLength&&t("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);e.buffer=buffer=a;Ga()}e.asm=k;e.usingWasm=!0;Za--;e.monitorRunDependencies&&e.monitorRunDependencies(Za);0==Za&&(null!==$a&&(clearInterval($a),$a=null),ab&&(a=ab,ab=null,a()))}function d(a){c(a.instance)}function g(a){b().then(function(a){return WebAssembly.instantiate(a,h)}).then(a,
function(a){t("failed to asynchronously prepare wasm: "+a);r(a)})}if("object"!==typeof WebAssembly)return t("no native wasm support detected"),!1;if(!(e.wasmMemory instanceof WebAssembly.Memory))return t("no native wasm Memory in use"),!1;a.memory=e.wasmMemory;h.global={NaN:NaN,Infinity:Infinity};h["global.Math"]=Math;h.env=a;Za++;e.monitorRunDependencies&&e.monitorRunDependencies(Za);if(e.instantiateWasm)try{return e.instantiateWasm(h,c)}catch(da){return t("Module.instantiateWasm callback failed with error: "+
da),!1}e.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||bb(f)||"function"!==typeof fetch?g(d):WebAssembly.instantiateStreaming(fetch(f,{credentials:"same-origin"}),h).then(d,function(a){t("wasm streaming compile failed: "+a);t("falling back to ArrayBuffer instantiation");g(d)});return{}}var d="canvaskit.wast",f="canvaskit.wasm",g="canvaskit.temp.asm.js";bb(d)||(d=ha(d));bb(f)||(f=ha(f));bb(g)||(g=ha(g));var h={global:null,env:null,asm2wasm:qa,parent:e},k=null;e.asmPreload=e.asm;
var m=e.reallocBuffer;e.reallocBuffer=function(a){if("asmjs"===l)var b=m(a);else a:{a=Ba(a,e.usingWasm?ya:za);var c=e.buffer.byteLength;if(e.usingWasm)try{b=-1!==e.wasmMemory.grow((a-c)/65536)?e.buffer=e.wasmMemory.buffer:null;break a}catch(H){b=null;break a}b=void 0}return b};var l="";e.asm=function(a,b){if(!b.table){a=e.wasmTableSize;void 0===a&&(a=1024);var d=e.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==d?new WebAssembly.Table({initial:a,
maximum:d,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);e.wasmTable=b.table}b.__memory_base||(b.__memory_base=e.STATIC_BASE);b.__table_base||(b.__table_base=0);b=c(b);assert(b,"no binaryen method succeeded.");return b}})();Ha=1024;u=Ha+684E3;Sa.push({wd:function(){cb()}},{wd:function(){db()}},{wd:function(){eb()}});e.STATIC_BASE=Ha;e.STATIC_BUMP=684E3;u+=16;var C={};
function fb(a){if(fb.wc){var b=w[a>>2];var c=w[b>>2]}else fb.wc=!0,C.USER=C.LOGNAME="web_user",C.PATH="/",C.PWD="/",C.HOME="/home/web_user",C.LANG="C.UTF-8",C._=e.thisProgram,c=Ia?Wa?gb(1024):na(1024):ma(1024),b=Ia?Wa?gb(256):na(256):ma(256),w[b>>2]=c,w[a>>2]=b;a=[];var d=0,f;for(f in C)if("string"===typeof C[f]){var g=f+"="+C[f];a.push(g);d+=g.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(f=0;f<a.length;f++){d=g=a[f];for(var h=c,k=0;k<d.length;++k)A[h++>>0]=d.charCodeAt(k);
A[h>>0]=0;w[b+4*f>>2]=c;c+=g.length+1}w[b+4*a.length>>2]=0}function hb(){return!!hb.wc}
var D={Wc:1,Ic:2,kg:3,ff:4,Vc:5,Nd:6,ze:7,Ff:8,Hc:9,Ne:10,Id:11,ug:11,Ld:12,ad:13,Ze:14,Rf:15,Jd:16,Kd:17,vg:18,cd:19,dd:20,bd:21,uc:22,Af:23,Zd:24,Mc:25,rg:26,$e:27,Nf:28,ed:29,hg:30,tf:31,ag:32,We:33,eg:34,Jf:42,cf:43,Oe:44,jf:45,kf:46,lf:47,sf:48,sg:49,Df:50,hf:51,Te:35,Gf:37,Fe:52,Ie:53,wg:54,Bf:55,Je:56,Ke:57,Ue:35,Le:59,Pf:60,Ef:61,og:62,Of:63,Kf:64,Lf:65,gg:66,Hf:67,Ce:68,lg:69,Pe:70,bg:71,vf:72,Xe:73,He:74,Wf:76,Ge:77,fg:78,mf:79,nf:80,rf:81,qf:82,pf:83,Qf:38,Md:39,wf:36,sd:40,Xf:95,$f:96,
Se:104,Cf:105,De:97,dg:91,Uf:88,Mf:92,ig:108,Re:111,Ae:98,Qe:103,zf:101,xf:100,pg:110,af:112,bf:113,ef:115,Ee:114,Ve:89,uf:90,cg:93,jg:94,Be:99,yf:102,gf:106,Sf:107,qg:109,tg:87,Ye:122,mg:116,Vf:95,If:123,df:84,Yf:75,Me:125,Tf:131,Zf:130,ng:86},ib={0:"Success",1:"Not super-user",2:"No such file or directory",3:"No such process",4:"Interrupted system call",5:"I/O error",6:"No such device or address",7:"Arg list too long",8:"Exec format error",9:"Bad file number",10:"No children",11:"No more processes",
12:"Not enough core",13:"Permission denied",14:"Bad address",15:"Block device required",16:"Mount device busy",17:"File exists",18:"Cross-device link",19:"No such device",20:"Not a directory",21:"Is a directory",22:"Invalid argument",23:"Too many open files in system",24:"Too many open files",25:"Not a typewriter",26:"Text file busy",27:"File too large",28:"No space left on device",29:"Illegal seek",30:"Read only file system",31:"Too many links",32:"Broken pipe",33:"Math arg out of domain of func",
34:"Math result not representable",35:"File locking deadlock error",36:"File or path name too long",37:"No record locks available",38:"Function not implemented",39:"Directory not empty",40:"Too many symbolic links",42:"No message of desired type",43:"Identifier removed",44:"Channel number out of range",45:"Level 2 not synchronized",46:"Level 3 halted",47:"Level 3 reset",48:"Link number out of range",49:"Protocol driver not attached",50:"No CSI structure available",51:"Level 2 halted",52:"Invalid exchange",
53:"Invalid request descriptor",54:"Exchange full",55:"No anode",56:"Invalid request code",57:"Invalid slot",59:"Bad font file fmt",60:"Device not a stream",61:"No data (for no delay io)",62:"Timer expired",63:"Out of streams resources",64:"Machine is not on the network",65:"Package not installed",66:"The object is remote",67:"The link has been severed",68:"Advertise error",69:"Srmount error",70:"Communication error on send",71:"Protocol error",72:"Multihop attempted",73:"Cross mount point (not really error)",
74:"Trying to read unreadable message",75:"Value too large for defined data type",76:"Given log. name not unique",77:"f.d. invalid for this operation",78:"Remote address changed",79:"Can   access a needed shared lib",80:"Accessing a corrupted shared lib",81:".lib section in a.out corrupted",82:"Attempting to link in too many libs",83:"Attempting to exec a shared library",84:"Illegal byte sequence",86:"Streams pipe error",87:"Too many users",88:"Socket operation on non-socket",89:"Destination address required",
90:"Message too long",91:"Protocol wrong type for socket",92:"Protocol not available",93:"Unknown protocol",94:"Socket type not supported",95:"Not supported",96:"Protocol family not supported",97:"Address family not supported by protocol family",98:"Address already in use",99:"Address not available",100:"Network interface is not configured",101:"Network is unreachable",102:"Connection reset by network",103:"Connection aborted",104:"Connection reset by peer",105:"No buffer space available",106:"Socket is already connected",
107:"Socket is not connected",108:"Can't send after socket shutdown",109:"Too many references",110:"Connection timed out",111:"Connection refused",112:"Host is down",113:"Host is unreachable",114:"Socket already connected",115:"Connection already in progress",116:"Stale file handle",122:"Quota exceeded",123:"No medium (in tape drive)",125:"Operation canceled",130:"Previous owner died",131:"State not recoverable"};function jb(a){e.___errno_location&&(w[e.___errno_location()>>2]=a);return a}
function kb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function lb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=kb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function mb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function nb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function ob(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=kb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var pb=[];function qb(a,b){pb[a]={input:[],output:[],Qc:b};rb(a,sb)}
var sb={open:function(a){var b=pb[a.node.rdev];if(!b)throw new E(D.cd);a.tty=b;a.seekable=!1},close:function(a){a.tty.Qc.flush(a.tty)},flush:function(a){a.tty.Qc.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Qc.Wd)throw new E(D.Nd);for(var f=0,g=0;g<d;g++){try{var h=a.tty.Qc.Wd(a.tty)}catch(k){throw new E(D.Vc);}if(void 0===h&&0===f)throw new E(D.Id);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.Qc.Dd)throw new E(D.Nd);
var f=0;try{if(0===c&&0===d)a.tty.Qc.flush(a.tty);else for(;f<d;)a.tty.Qc.Dd(a.tty,b[c+f]),f++}catch(g){throw new E(D.Vc);}d&&(a.node.timestamp=Date.now());return f}},ub={Wd:function(a){if(!a.input.length){var b=null;if(ea){var c=new Buffer(256),d=0,f=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(h){}}try{d=fs.readSync(f,c,0,256,null)}catch(h){if(-1!=h.toString().indexOf("EOF"))d=0;else throw h;}g&&fs.closeSync(f);0<d?b=c.slice(0,d).toString("utf-8"):
b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=tb(b)}return a.input.shift()},Dd:function(a,b){null===b||10===b?(la(ua(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(la(ua(a.output,0)),a.output=[])}},vb={Dd:function(a,b){null===b||10===b?(t(ua(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},
flush:function(a){a.output&&0<a.output.length&&(t(ua(a.output,0)),a.output=[])}},F={Fc:null,Jc:function(){return F.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new E(D.Wc);F.Fc||(F.Fc={dir:{node:{Ec:F.oc.Ec,Gc:F.oc.Gc,lookup:F.oc.lookup,od:F.oc.od,rename:F.oc.rename,unlink:F.oc.unlink,rmdir:F.oc.rmdir,readdir:F.oc.readdir,symlink:F.oc.symlink},stream:{Pc:F.pc.Pc}},file:{node:{Ec:F.oc.Ec,Gc:F.oc.Gc},stream:{Pc:F.pc.Pc,read:F.pc.read,write:F.pc.write,
Qd:F.pc.Qd,pd:F.pc.pd,rd:F.pc.rd}},link:{node:{Ec:F.oc.Ec,Gc:F.oc.Gc,readlink:F.oc.readlink},stream:{}},Rd:{node:{Ec:F.oc.Ec,Gc:F.oc.Gc},stream:wb}});c=xb(a,b,c,d);16384===(c.mode&61440)?(c.oc=F.Fc.dir.node,c.pc=F.Fc.dir.stream,c.nc={}):32768===(c.mode&61440)?(c.oc=F.Fc.file.node,c.pc=F.Fc.file.stream,c.sc=0,c.nc=null):40960===(c.mode&61440)?(c.oc=F.Fc.link.node,c.pc=F.Fc.link.stream):8192===(c.mode&61440)&&(c.oc=F.Fc.Rd.node,c.pc=F.Fc.Rd.stream);c.timestamp=Date.now();a&&(a.nc[b]=c);return c},je:function(a){if(a.nc&&
a.nc.subarray){for(var b=[],c=0;c<a.sc;++c)b.push(a.nc[c]);return b}return a.nc},Ag:function(a){return a.nc?a.nc.subarray?a.nc.subarray(0,a.sc):new Uint8Array(a.nc):new Uint8Array},Td:function(a,b){a.nc&&a.nc.subarray&&b>a.nc.length&&(a.nc=F.je(a),a.sc=a.nc.length);if(!a.nc||a.nc.subarray){var c=a.nc?a.nc.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.nc,a.nc=new Uint8Array(b),0<a.sc&&a.nc.set(c.subarray(0,a.sc),0))}else for(!a.nc&&0<b&&(a.nc=[]);a.nc.length<b;)a.nc.push(0)},
ue:function(a,b){if(a.sc!=b)if(0==b)a.nc=null,a.sc=0;else{if(!a.nc||a.nc.subarray){var c=a.nc;a.nc=new Uint8Array(new ArrayBuffer(b));c&&a.nc.set(c.subarray(0,Math.min(b,a.sc)))}else if(a.nc||(a.nc=[]),a.nc.length>b)a.nc.length=b;else for(;a.nc.length<b;)a.nc.push(0);a.sc=b}},oc:{Ec:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.sc:40960===(a.mode&61440)?b.size=
a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.de=4096;b.blocks=Math.ceil(b.size/b.de);return b},Gc:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&F.ue(a,b.size)},lookup:function(){throw yb[D.Ic];},od:function(a,b,c,d){return F.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=zb(b,c)}catch(g){}if(d)for(var f in d.nc)throw new E(D.Md);
}delete a.parent.nc[a.name];a.name=c;b.nc[c]=a;a.parent=b},unlink:function(a,b){delete a.nc[b]},rmdir:function(a,b){var c=zb(a,b),d;for(d in c.nc)throw new E(D.Md);delete a.nc[b]},readdir:function(a){var b=[".",".."],c;for(c in a.nc)a.nc.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=F.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new E(D.uc);return a.link}},pc:{read:function(a,b,c,d,f){var g=a.node.nc;if(f>=a.node.sc)return 0;a=
Math.min(a.node.sc-f,d);assert(0<=a);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){g=!1;if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.nc||a.nc.subarray)){if(g)return a.nc=b.subarray(c,c+d),a.sc=d;if(0===a.sc&&0===f)return a.nc=new Uint8Array(b.subarray(c,c+d)),a.sc=d;if(f+d<=a.sc)return a.nc.set(b.subarray(c,c+d),f),d}F.Td(a,f+d);if(a.nc.subarray&&b.subarray)a.nc.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.nc[f+
g]=b[c+g];a.sc=Math.max(a.sc,f+d);return d},Pc:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.sc);if(0>b)throw new E(D.uc);return b},Qd:function(a,b,c){F.Td(a.node,b+c);a.node.sc=Math.max(a.node.sc,b+c)},pd:function(a,b,c,d,f,g,h){if(32768!==(a.node.mode&61440))throw new E(D.cd);c=a.node.nc;if(h&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<f||f+d<a.node.sc)c.subarray?c=c.subarray(f,f+d):c=Array.prototype.slice.call(c,f,f+d);a=!0;d=gb(d);if(!d)throw new E(D.Ld);b.set(c,
d)}else a=!1,d=c.byteOffset;return{rc:d,ud:a}},rd:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new E(D.cd);if(f&2)return 0;F.pc.write(a,b,0,d,c,!1);return 0}}};u+=16;u+=16;u+=16;var Ab=null,Bb={},G=[],Cb=1,Db=null,Eb=!0,Fb={},E=null,yb={};
function I(a,b){a=ob("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Vd:!0,Ed:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Ed)throw new E(D.sd);a=kb(a.split("/").filter(function(a){return!!a}),!1);var f=Ab;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=zb(f,a[d]);c=lb(c+"/"+a[d]);f.qd&&(!g||g&&b.Vd)&&(f=f.qd.root);if(!g||b.Sc)for(g=0;40960===(f.mode&61440);)if(f=Gb(c),c=ob(mb(c),f),f=I(c,{Ed:b.Ed}).node,40<g++)throw new E(D.sd);}return{path:c,node:f}}
function Hb(a){for(var b;;){if(a===a.parent)return a=a.Jc.Xd,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Ib(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Db.length}function Jb(a){var b=Ib(a.parent.id,a.name);a.qe=Db[b];Db[b]=a}function zb(a,b){var c;if(c=(c=Kb(a,"x"))?c:a.oc.lookup?0:D.ad)throw new E(c,a);for(c=Db[Ib(a.id,b)];c;c=c.qe){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.oc.lookup(a,b)}
function xb(a,b,c,d){Lb||(Lb=function(a,b,c,d){a||(a=this);this.parent=a;this.Jc=a.Jc;this.qd=null;this.id=Cb++;this.name=b;this.mode=c;this.oc={};this.pc={};this.rdev=d},Lb.prototype={},Object.defineProperties(Lb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Bd:{get:function(){return 16384===(this.mode&61440)}},Ad:{get:function(){return 8192===
(this.mode&61440)}}}));a=new Lb(a,b,c,d);Jb(a);return a}var Mb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Nb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Kb(a,b){if(Eb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return D.ad}else return D.ad;return 0}
function Ob(a,b){try{return zb(a,b),D.Kd}catch(c){}return Kb(a,"wx")}function Pb(a){var b=4096;for(a=a||0;a<=b;a++)if(!G[a])return a;throw new E(D.Zd);}function Qb(a,b){Rb||(Rb=function(){},Rb.prototype={},Object.defineProperties(Rb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Rb,d;for(d in a)c[d]=a[d];a=c;b=Pb(b);a.fd=b;return G[b]=a}var wb={open:function(a){a.pc=Bb[a.node.rdev].pc;a.pc.open&&a.pc.open(a)},Pc:function(){throw new E(D.ed);}};
function rb(a,b){Bb[a]={pc:b}}function Sb(a,b){var c="/"===b,d=!b;if(c&&Ab)throw new E(D.Jd);if(!c&&!d){var f=I(b,{Vd:!1});b=f.path;f=f.node;if(f.qd)throw new E(D.Jd);if(16384!==(f.mode&61440))throw new E(D.dd);}b={type:a,Dg:{},Xd:b,pe:[]};a=a.Jc(b);a.Jc=b;b.root=a;c?Ab=a:f&&(f.qd=b,f.Jc&&f.Jc.pe.push(b))}function Tb(a,b,c){var d=I(a,{parent:!0}).node;a=nb(a);if(!a||"."===a||".."===a)throw new E(D.uc);var f=Ob(d,a);if(f)throw new E(f);if(!d.oc.od)throw new E(D.Wc);return d.oc.od(d,a,b,c)}
function J(a){Tb(a,16895,0)}function Ub(a,b,c){"undefined"===typeof c&&(c=b,b=438);Tb(a,b|8192,c)}function Vb(a,b){if(!ob(a))throw new E(D.Ic);var c=I(b,{parent:!0}).node;if(!c)throw new E(D.Ic);b=nb(b);var d=Ob(c,b);if(d)throw new E(d);if(!c.oc.symlink)throw new E(D.Wc);c.oc.symlink(c,b,a)}function Gb(a){a=I(a).node;if(!a)throw new E(D.Ic);if(!a.oc.readlink)throw new E(D.uc);return ob(Hb(a.parent),a.oc.readlink(a))}
function Wb(a){a=I(a,{Sc:!0}).node;if(!a)throw new E(D.Ic);if(!a.oc.Ec)throw new E(D.Wc);return a.oc.Ec(a)}
function Xb(a,b,c,d){if(""===a)throw new E(D.Ic);if("string"===typeof b){var f=Mb[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=lb(a);try{g=I(a,{Sc:!(b&131072)}).node}catch(k){}}f=!1;if(b&64)if(g){if(b&128)throw new E(D.Kd);}else g=Tb(a,c,0),f=!0;if(!g)throw new E(D.Ic);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&16384!==(g.mode&61440))throw new E(D.dd);if(!f&&(c=g?40960===(g.mode&
61440)?D.sd:16384===(g.mode&61440)&&("r"!==Nb(b)||b&512)?D.bd:Kb(g,Nb(b)):D.Ic))throw new E(c);if(b&512){c=g;var h;"string"===typeof c?h=I(c,{Sc:!0}).node:h=c;if(!h.oc.Gc)throw new E(D.Wc);if(16384===(h.mode&61440))throw new E(D.bd);if(32768!==(h.mode&61440))throw new E(D.uc);if(c=Kb(h,"w"))throw new E(c);h.oc.Gc(h,{size:0,timestamp:Date.now()})}b&=-641;d=Qb({node:g,path:Hb(g),flags:b,seekable:!0,position:0,pc:g.pc,xe:[],error:!1},d);d.pc.open&&d.pc.open(d);!e.logReadFiles||b&1||(Yb||(Yb={}),a in
Yb||(Yb[a]=1,console.log("FS.trackingDelegate error on read file: "+a)));try{Fb.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),Fb.onOpenFile(a,g))}catch(k){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+k.message)}return d}function Zb(a){if(null===a.fd)throw new E(D.Hc);a.Oc&&(a.Oc=null);try{a.pc.close&&a.pc.close(a)}catch(b){throw b;}finally{G[a.fd]=null}a.fd=null}
function $b(a,b,c){if(null===a.fd)throw new E(D.Hc);if(!a.seekable||!a.pc.Pc)throw new E(D.ed);a.position=a.pc.Pc(a,b,c);a.xe=[]}function ac(a,b,c,d,f){if(0>d||0>f)throw new E(D.uc);if(null===a.fd)throw new E(D.Hc);if(1===(a.flags&2097155))throw new E(D.Hc);if(16384===(a.node.mode&61440))throw new E(D.bd);if(!a.pc.read)throw new E(D.uc);var g="undefined"!==typeof f;if(!g)f=a.position;else if(!a.seekable)throw new E(D.ed);b=a.pc.read(a,b,c,d,f);g||(a.position+=b);return b}
function bc(a){var b={encoding:"binary"};b=b||{};b.flags=b.flags||"r";b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var c,d=Xb(a,b.flags);a=Wb(a).size;var f=new Uint8Array(a);ac(d,f,0,a,0);"utf8"===b.encoding?c=ua(f,0):"binary"===b.encoding&&(c=f);Zb(d);return c}
function cc(){E||(E=function(a,b){this.node=b;this.ve=function(a){this.vc=a;for(var b in D)if(D[b]===a){this.code=b;break}};this.ve(a);this.message=ib[a];this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},E.prototype=Error(),E.prototype.constructor=E,[D.Ic].forEach(function(a){yb[a]=new E(a);yb[a].stack="<generic error, no stack>"}))}var dc;function ec(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function fc(a){try{var b=I(a,{Sc:!0});a=b.path}catch(g){}var c=!1,d=0,f=null;try{b=I(a,{parent:!0}),b=I(a,{Sc:!0}),c=!0,f=b.node}catch(g){d=g.vc}if(c)return f;jb(d);return null}
function hc(a,b,c){a=lb("/dev/"+a);var d=ec(!!b,!!c);ic||(ic=64);var f=ic++<<8|0;rb(f,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,d,f){for(var g=0,h=0;h<f;h++){try{var k=b()}catch(K){throw new E(D.Vc);}if(void 0===k&&0===g)throw new E(D.Id);if(null===k||void 0===k)break;g++;c[d+h]=k}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,d,f){for(var g=0;g<f;g++)try{c(b[d+g])}catch(q){throw new E(D.Vc);}f&&(a.node.timestamp=Date.now());
return g}});Ub(a,d,f)}var ic;function jc(a){if(!(a.Ad||a.Bd||a.link||a.nc)){var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(e.read)try{a.nc=tb(e.read(a.url)),a.sc=a.nc.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||jb(D.Vc)}}
var FS={},Lb,Rb,Yb,kc={};function lc(a,b){try{var c=Wb(a)}catch(d){if(d&&d.node&&lb(a)!==lb(Hb(d.node)))return-D.dd;throw d;}w[b>>2]=c.dev;w[b+4>>2]=0;w[b+8>>2]=c.ino;w[b+12>>2]=c.mode;w[b+16>>2]=c.nlink;w[b+20>>2]=c.uid;w[b+24>>2]=c.gid;w[b+28>>2]=c.rdev;w[b+32>>2]=0;w[b+36>>2]=c.size;w[b+40>>2]=4096;w[b+44>>2]=c.blocks;w[b+48>>2]=c.atime.getTime()/1E3|0;w[b+52>>2]=0;w[b+56>>2]=c.mtime.getTime()/1E3|0;w[b+60>>2]=0;w[b+64>>2]=c.ctime.getTime()/1E3|0;w[b+68>>2]=0;w[b+72>>2]=c.ino;return 0}var L=0;
function M(){L+=4;return w[L-4>>2]}function N(){var a=G[M()];if(!a)throw new E(D.Hc);return a}var mc={};function nc(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function oc(a){return this.fromWireType(B[a>>2])}var pc={},qc={},rc={};function sc(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function tc(a,b){a=sc(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function uc(a){var b=Error,c=tc(a,function(b){this.name=a;this.message=b;b=Error(b).stack;void 0!==b&&(this.stack=this.toString()+"\n"+b.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var vc=void 0;function wc(a){throw new vc(a);}function O(a,b,c){function d(b){b=c(b);b.length!==a.length&&wc("Mismatched type converter count");for(var d=0;d<a.length;++d)P(a[d],b[d])}a.forEach(function(a){rc[a]=b});var f=Array(b.length),g=[],h=0;b.forEach(function(a,b){qc.hasOwnProperty(a)?f[b]=qc[a]:(g.push(a),pc.hasOwnProperty(a)||(pc[a]=[]),pc[a].push(function(){f[b]=qc[a];++h;h===g.length&&d(f)}))});0===g.length&&d(f)}var xc={};
function yc(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var zc=void 0;function Q(a){for(var b="";z[a];)b+=zc[z[a++]];return b}var Ac=void 0;function R(a){throw new Ac(a);}
function P(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||R('type "'+d+'" must have a positive integer typeid pointer');if(qc.hasOwnProperty(a)){if(c.le)return;R("Cannot register type '"+d+"' twice")}qc[a]=b;delete rc[a];pc.hasOwnProperty(a)&&(b=pc[a],delete pc[a],b.forEach(function(a){a()}))}function Bc(a){R(a.mc.tc.qc.name+" instance already deleted")}var Cc=void 0,Dc=[];
function Ec(){for(;Dc.length;){var a=Dc.pop();a.mc.Rc=!1;a["delete"]()}}function S(){}var Fc={};function Gc(a,b,c){if(void 0===a[b].xc){var d=a[b];a[b]=function(){a[b].xc.hasOwnProperty(arguments.length)||R("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].xc+")!");return a[b].xc[arguments.length].apply(this,arguments)};a[b].xc=[];a[b].xc[d.ld]=d}}
function Hc(a,b,c){e.hasOwnProperty(a)?((void 0===c||void 0!==e[a].xc&&void 0!==e[a].xc[c])&&R("Cannot register public name '"+a+"' twice"),Gc(e,a,a),e.hasOwnProperty(c)&&R("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),e[a].xc[c]=b):(e[a]=b,void 0!==c&&(e[a].Cg=c))}function Ic(a,b,c,d,f,g,h,k){this.name=a;this.constructor=b;this.Tc=c;this.Bc=d;this.Dc=f;this.ie=g;this.$c=h;this.ge=k;this.se=[]}
function Jc(a,b,c){for(;b!==c;)b.$c||R("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.$c(a),b=b.Dc;return a}function Kc(a,b){if(null===b)return this.Cd&&R("null is not a valid "+this.name),0;b.mc||R('Cannot pass "'+Lc(b)+'" as a '+this.name);b.mc.rc||R("Cannot pass deleted object as a pointer of type "+this.name);return Jc(b.mc.rc,b.mc.tc.qc,this.qc)}
function Mc(a,b){if(null===b){this.Cd&&R("null is not a valid "+this.name);if(this.nd){var c=this.Zc();null!==a&&a.push(this.Bc,c);return c}return 0}b.mc||R('Cannot pass "'+Lc(b)+'" as a '+this.name);b.mc.rc||R("Cannot pass deleted object as a pointer of type "+this.name);!this.md&&b.mc.tc.md&&R("Cannot convert argument of type "+(b.mc.Cc?b.mc.Cc.name:b.mc.tc.name)+" to parameter type "+this.name);c=Jc(b.mc.rc,b.mc.tc.qc,this.qc);if(this.nd)switch(void 0===b.mc.Ac&&R("Passing raw pointer to smart pointer is illegal"),
this.we){case 0:b.mc.Cc===this?c=b.mc.Ac:R("Cannot convert argument of type "+(b.mc.Cc?b.mc.Cc.name:b.mc.tc.name)+" to parameter type "+this.name);break;case 1:c=b.mc.Ac;break;case 2:if(b.mc.Cc===this)c=b.mc.Ac;else{var d=b.clone();c=this.te(c,Nc(function(){d["delete"]()}));null!==a&&a.push(this.Bc,c)}break;default:R("Unsupporting sharing policy")}return c}
function Oc(a,b){if(null===b)return this.Cd&&R("null is not a valid "+this.name),0;b.mc||R('Cannot pass "'+Lc(b)+'" as a '+this.name);b.mc.rc||R("Cannot pass deleted object as a pointer of type "+this.name);b.mc.tc.md&&R("Cannot convert argument of type "+b.mc.tc.name+" to parameter type "+this.name);return Jc(b.mc.rc,b.mc.tc.qc,this.qc)}function Qc(a,b,c){if(b===c)return a;if(void 0===c.Dc)return null;a=Qc(a,b,c.Dc);return null===a?null:c.ge(a)}var Rc={};
function Sc(a,b){for(void 0===b&&R("ptr should not be undefined");a.Dc;)b=a.$c(b),a=a.Dc;return Rc[b]}function Tc(a,b){b.tc&&b.rc||wc("makeClassHandle requires ptr and ptrType");!!b.Cc!==!!b.Ac&&wc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Object.create(a,{mc:{value:b}})}
function T(a,b,c,d,f,g,h,k,m,l,q){this.name=a;this.qc=b;this.Cd=c;this.md=d;this.nd=f;this.re=g;this.we=h;this.Yd=k;this.Zc=m;this.te=l;this.Bc=q;f||void 0!==b.Dc?this.toWireType=Mc:(this.toWireType=d?Kc:Oc,this.zc=null)}function Uc(a,b,c){e.hasOwnProperty(a)||wc("Replacing nonexistant public symbol");void 0!==e[a].xc&&void 0!==c?e[a].xc[c]=b:(e[a]=b,e[a].ld=c)}
function U(a,b){a=Q(a);if(void 0!==e["FUNCTION_TABLE_"+a])var c=e["FUNCTION_TABLE_"+a][b];else if("undefined"!==typeof FUNCTION_TABLE)c=FUNCTION_TABLE[b];else{c=e["dynCall_"+a];void 0===c&&(c=e["dynCall_"+a.replace(/f/g,"d")],void 0===c&&R("No dynCall invoker for signature: "+a));for(var d=[],f=1;f<a.length;++f)d.push("a"+f);f="return function "+("dynCall_"+a+"_"+b)+"("+d.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(d.length?", ":"")+d.join(", ")+");\n";c=(new Function("dynCall","rawFunction",
f+"};\n"))(c,b)}"function"!==typeof c&&R("unknown function pointer with signature "+a+": "+b);return c}var Vc=void 0;function Wc(a){a=Xc(a);var b=Q(a);V(a);return b}function Yc(a,b){function c(a){f[a]||qc[a]||(rc[a]?rc[a].forEach(c):(d.push(a),f[a]=!0))}var d=[],f={};b.forEach(c);throw new Vc(a+": "+d.map(Wc).join([", "]));}function Zc(a,b){for(var c=[],d=0;d<a;d++)c.push(w[(b>>2)+d]);return c}
function $c(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=tc(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function ad(a,b,c,d,f){var g=b.length;2>g&&R("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,k=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].zc){k=!0;break}var m="void"!==b[0].name,l="",q="";for(c=0;c<g-2;++c)l+=(0!==c?", ":"")+"arg"+c,q+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+sc(a)+"("+l+") {\nif (arguments.length !== "+(g-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(g-2)+" args!');\n}\n";k&&(a+="var destructors = [];\n");var v=k?"destructors":"null";l="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[R,d,f,nc,b[0],b[1]];h&&(a+="var thisWired = classParam.toWireType("+v+", this);\n");for(c=0;c<g-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+v+", arg"+c+"); // "+b[c+2].name+"\n",l.push("argType"+c),d.push(b[c+2]);h&&(q="thisWired"+(0<q.length?", ":"")+q);a+=(m?"var rv = ":"")+"invoker(fn"+(0<q.length?", ":"")+q+");\n";if(k)a+=
"runDestructors(destructors);\n";else for(c=h?1:2;c<b.length;++c)g=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].zc&&(a+=g+"_dtor("+g+"); // "+b[c].name+"\n",l.push(g+"_dtor"),d.push(b[c].zc));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");l.push(a+"}\n");return $c(l).apply(null,d)}var bd=[],W=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function cd(a){4<a&&0===--W[a].Uc&&(W[a]=void 0,bd.push(a))}
function Nc(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=bd.length?bd.pop():W.length;W[b]={Uc:1,value:a};return b}}function dd(a,b,c){switch(b){case 0:return function(a){return this.fromWireType((c?A:z)[a])};case 1:return function(a){return this.fromWireType((c?Ca:Da)[a>>1])};case 2:return function(a){return this.fromWireType((c?w:B)[a>>2])};default:throw new TypeError("Unknown integer type: "+a);}}
function ed(a,b){var c=qc[a];void 0===c&&R(b+" has unknown type "+Wc(a));return c}function Lc(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function fd(a,b){switch(b){case 2:return function(a){return this.fromWireType(Ea[a>>2])};case 3:return function(a){return this.fromWireType(Fa[a>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function gd(a,b,c){switch(b){case 0:return c?function(a){return A[a]}:function(a){return z[a]};case 1:return c?function(a){return Ca[a>>1]}:function(a){return Da[a>>1]};case 2:return c?function(a){return w[a>>2]}:function(a){return B[a>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var hd={},X={},id={};function jd(a,b){e.setThrew(a,b||1);throw"longjmp";}
function kd(a){if(0===a)return 0;a=ta(a);if(!C.hasOwnProperty(a))return 0;kd.wc&&V(kd.wc);a=C[a];var b=xa(a)+1,c=gb(b);c&&wa(a,A,c,b);kd.wc=c;return kd.wc}var ld={},md=1;function nd(a,b){nd.wc||(nd.wc={});a in nd.wc||(e.dynCall_v(b),nd.wc[a]=1)}cc();Db=Array(4096);Sb(F,"/");J("/tmp");J("/home");J("/home/web_user");
(function(){J("/dev");rb(259,{read:function(){return 0},write:function(a,b,f,g){return g}});Ub("/dev/null",259);qb(1280,ub);qb(1536,vb);Ub("/dev/tty",1280);Ub("/dev/tty1",1536);if("undefined"!==typeof crypto){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else ea?b=function(){return require("crypto").randomBytes(1)[0]}:b=function(){r("random_device")};hc("random",b);hc("urandom",b);J("/dev/shm");J("/dev/shm/tmp")})();J("/proc");J("/proc/self");J("/proc/self/fd");
Sb({Jc:function(){var a=xb("/proc/self","fd",16895,73);a.oc={lookup:function(a,c){var b=G[+c];if(!b)throw new E(D.Hc);a={parent:null,Jc:{Xd:"fake"},oc:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");
Sa.unshift(function(){if(!e.noFSInit&&!dc){assert(!dc,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");dc=!0;cc();e.stdin=e.stdin;e.stdout=e.stdout;e.stderr=e.stderr;e.stdin?hc("stdin",e.stdin):Vb("/dev/tty","/dev/stdin");e.stdout?hc("stdout",null,e.stdout):Vb("/dev/tty","/dev/stdout");e.stderr?hc("stderr",null,e.stderr):Vb("/dev/tty1","/dev/stderr");var a=Xb("/dev/stdin",
"r");assert(0===a.fd,"invalid handle for stdin ("+a.fd+")");a=Xb("/dev/stdout","w");assert(1===a.fd,"invalid handle for stdout ("+a.fd+")");a=Xb("/dev/stderr","w");assert(2===a.fd,"invalid handle for stderr ("+a.fd+")")}});Ta.push(function(){Eb=!1});Ua.push(function(){dc=!1;var a=e._fflush;a&&a(0);for(a=0;a<G.length;a++){var b=G[a];b&&Zb(b)}});Sa.unshift(function(){});Ua.push(function(){});vc=e.InternalError=uc("InternalError");for(var od=Array(256),pd=0;256>pd;++pd)od[pd]=String.fromCharCode(pd);
zc=od;Ac=e.BindingError=uc("BindingError");S.prototype.isAliasOf=function(a){if(!(this instanceof S&&a instanceof S))return!1;var b=this.mc.tc.qc,c=this.mc.rc,d=a.mc.tc.qc;for(a=a.mc.rc;b.Dc;)c=b.$c(c),b=b.Dc;for(;d.Dc;)a=d.$c(a),d=d.Dc;return b===d&&c===a};
S.prototype.clone=function(){this.mc.rc||Bc(this);if(this.mc.Yc)return this.mc.count.value+=1,this;var a=this.mc;a=Object.create(Object.getPrototypeOf(this),{mc:{value:{count:a.count,Rc:a.Rc,Yc:a.Yc,rc:a.rc,tc:a.tc,Ac:a.Ac,Cc:a.Cc}}});a.mc.count.value+=1;a.mc.Rc=!1;return a};
S.prototype["delete"]=function(){this.mc.rc||Bc(this);this.mc.Rc&&!this.mc.Yc&&R("Object already scheduled for deletion");--this.mc.count.value;if(0===this.mc.count.value){var a=this.mc;a.Ac?a.Cc.Bc(a.Ac):a.tc.qc.Bc(a.rc)}this.mc.Yc||(this.mc.Ac=void 0,this.mc.rc=void 0)};S.prototype.isDeleted=function(){return!this.mc.rc};
S.prototype.deleteLater=function(){this.mc.rc||Bc(this);this.mc.Rc&&!this.mc.Yc&&R("Object already scheduled for deletion");Dc.push(this);1===Dc.length&&Cc&&Cc(Ec);this.mc.Rc=!0;return this};T.prototype.ke=function(a){this.Yd&&(a=this.Yd(a));return a};T.prototype.Sd=function(a){this.Bc&&this.Bc(a)};T.prototype.argPackAdvance=8;T.prototype.readValueFromPointer=oc;T.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
T.prototype.fromWireType=function(a){function b(){return this.nd?Tc(this.qc.Tc,{tc:this.re,rc:c,Cc:this,Ac:a}):Tc(this.qc.Tc,{tc:this,rc:a})}var c=this.ke(a);if(!c)return this.Sd(a),null;var d=Sc(this.qc,c);if(void 0!==d){if(0===d.mc.count.value)return d.mc.rc=c,d.mc.Ac=a,d.clone();d=d.clone();this.Sd(a);return d}d=this.qc.ie(c);d=Fc[d];if(!d)return b.call(this);d=this.md?d.fe:d.pointerType;var f=Qc(c,this.qc,d.qc);return null===f?b.call(this):this.nd?Tc(d.qc.Tc,{tc:d,rc:f,Cc:this,Ac:a}):Tc(d.qc.Tc,
{tc:d,rc:f})};e.getInheritedInstanceCount=function(){return Object.keys(Rc).length};e.getLiveInheritedInstances=function(){var a=[],b;for(b in Rc)Rc.hasOwnProperty(b)&&a.push(Rc[b]);return a};e.flushPendingDeletes=Ec;e.setDelayFunction=function(a){Cc=a;Dc.length&&Cc&&Cc(Ec)};Vc=e.UnboundTypeError=uc("UnboundTypeError");e.count_emval_handles=function(){for(var a=0,b=5;b<W.length;++b)void 0!==W[b]&&++a;return a};e.get_first_emval=function(){for(var a=5;a<W.length;++a)if(void 0!==W[a])return W[a];return null};
x=ma(4);Ja=Ka=pa(u);La=Ja+Pa;Ma=pa(La);w[x>>2]=Ma;Ia=!0;function tb(a){var b=Array(xa(a)+1);a=wa(a,b,0,b.length);b.length=a;return b}e.wasmTableSize=3896;e.wasmMaxTableSize=3896;e.be={};
e.ce={d:r,Ea:oa,ya:function(){return y},sa:function(){r("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+y+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")},oa:function(a){var b=Y();try{return e.dynCall_i(a)}catch(c){Z(b);if("number"!==typeof c&&"longjmp"!==c)throw c;e.setThrew(1,0)}},i:function(a,
b){var c=Y();try{return e.dynCall_ii(a,b)}catch(d){Z(c);if("number"!==typeof d&&"longjmp"!==d)throw d;e.setThrew(1,0)}},n:function(a,b,c){var d=Y();try{return e.dynCall_iii(a,b,c)}catch(f){Z(d);if("number"!==typeof f&&"longjmp"!==f)throw f;e.setThrew(1,0)}},j:function(a,b,c,d){var f=Y();try{return e.dynCall_iiii(a,b,c,d)}catch(g){Z(f);if("number"!==typeof g&&"longjmp"!==g)throw g;e.setThrew(1,0)}},y:function(a,b,c,d,f){var g=Y();try{return e.dynCall_iiiii(a,b,c,d,f)}catch(h){Z(g);if("number"!==typeof h&&
"longjmp"!==h)throw h;e.setThrew(1,0)}},X:function(a,b,c,d,f,g,h){var k=Y();try{return e.dynCall_iiiiiii(a,b,c,d,f,g,h)}catch(m){Z(k);if("number"!==typeof m&&"longjmp"!==m)throw m;e.setThrew(1,0)}},Da:function(a){var b=Y();try{e.dynCall_v(a)}catch(c){Z(b);if("number"!==typeof c&&"longjmp"!==c)throw c;e.setThrew(1,0)}},h:function(a,b){var c=Y();try{e.dynCall_vi(a,b)}catch(d){Z(c);if("number"!==typeof d&&"longjmp"!==d)throw d;e.setThrew(1,0)}},g:function(a,b,c){var d=Y();try{e.dynCall_vii(a,b,c)}catch(f){Z(d);
if("number"!==typeof f&&"longjmp"!==f)throw f;e.setThrew(1,0)}},o:function(a,b,c,d){var f=Y();try{e.dynCall_viii(a,b,c,d)}catch(g){Z(f);if("number"!==typeof g&&"longjmp"!==g)throw g;e.setThrew(1,0)}},k:function(a,b,c,d,f){var g=Y();try{e.dynCall_viiii(a,b,c,d,f)}catch(h){Z(g);if("number"!==typeof h&&"longjmp"!==h)throw h;e.setThrew(1,0)}},Ca:function(a,b,c,d,f,g){var h=Y();try{e.dynCall_viiiii(a,b,c,d,f,g)}catch(k){Z(h);if("number"!==typeof k&&"longjmp"!==k)throw k;e.setThrew(1,0)}},Ba:function(a,
b,c,d,f,g,h,k,m,l){var q=Y();try{e.dynCall_viiiiiiiii(a,b,c,d,f,g,h,k,m,l)}catch(v){Z(q);if("number"!==typeof v&&"longjmp"!==v)throw v;e.setThrew(1,0)}},Aa:fb,W:function(a){return gb(a)},za:function(){sa=!0;throw"Pure virtual function called!";},V:function(a){"uncaught_exception"in hb?hb.wc++:hb.wc=1;throw a+" - Exception catching is disabled, this exception cannot be caught. Compile with -s DISABLE_EXCEPTION_CATCHING=0 or DISABLE_EXCEPTION_CATCHING=2 to catch.";},H:function(){},U:jb,xa:function(a,
b){L=b;try{var c=N();M();var d=M(),f=M(),g=M();$b(c,d,g);w[f>>2]=c.position;c.Oc&&0===d&&0===g&&(c.Oc=null);return 0}catch(h){return"undefined"!==typeof FS&&h instanceof E||r(h),-h.vc}},wa:function(a,b){L=b;try{var c=N(),d=M();a:{var f=M();for(b=a=0;b<f;b++){var g=w[d+(8*b+4)>>2],h=ac(c,A,w[d+8*b>>2],g,void 0);if(0>h){var k=-1;break a}a+=h;if(h<g)break}k=a}return k}catch(m){return"undefined"!==typeof FS&&m instanceof E||r(m),-m.vc}},T:function(a,b){L=b;try{var c=N(),d=M();a:{var f=M();for(b=a=0;b<
f;b++){var g=c,h=w[d+8*b>>2],k=w[d+(8*b+4)>>2],m=void 0,l=A;if(0>k||0>m)throw new E(D.uc);if(null===g.fd)throw new E(D.Hc);if(0===(g.flags&2097155))throw new E(D.Hc);if(16384===(g.node.mode&61440))throw new E(D.bd);if(!g.pc.write)throw new E(D.uc);g.flags&1024&&$b(g,0,2);var q="undefined"!==typeof m;if(!q)m=g.position;else if(!g.seekable)throw new E(D.ed);var v=g.pc.write(g,l,h,k,m,void 0);q||(g.position+=v);try{if(g.path&&Fb.onWriteToFile)Fb.onWriteToFile(g.path)}catch(da){console.log("FS.trackingDelegate['onWriteToFile']('"+
path+"') threw an exception: "+da.message)}var K=v;if(0>K){var H=-1;break a}a+=K}H=a}return H}catch(da){return"undefined"!==typeof FS&&da instanceof E||r(da),-da.vc}},va:function(a,b){L=b;try{var c=N(),d=M(),f=M();assert(0===M());var g=M(),h=M();0<=g?assert(0===h):assert(-1===h);return ac(c,A,d,f,g)}catch(k){return"undefined"!==typeof FS&&k instanceof E||r(k),-k.vc}},ua:function(a,b){L=b;try{var c=M(),d=M(),f=M(),g=M(),h=M(),k=M();k<<=12;a=!1;if(-1===h){var m=qd(16384,d);if(!m)return-D.Ld;rd(m,0,
d);a=!0}else{var l=G[h];if(!l)return-D.Hc;b=z;if(1===(l.flags&2097155))throw new E(D.ad);if(!l.pc.pd)throw new E(D.cd);var q=l.pc.pd(l,b,c,d,k,f,g);m=q.rc;a=q.ud}kc[m]={oe:m,ne:d,ud:a,fd:h,flags:g};return m}catch(v){return"undefined"!==typeof FS&&v instanceof E||r(v),-v.vc}},S:function(a,b){L=b;try{var c=ta(M()),d=M();return lc(c,d)}catch(f){return"undefined"!==typeof FS&&f instanceof E||r(f),-f.vc}},ta:function(a,b){L=b;try{var c=N(),d=M();return lc(c.path,d)}catch(f){return"undefined"!==typeof FS&&
f instanceof E||r(f),-f.vc}},ra:function(a,b){L=b;try{var c=N(),d=M(),f=M();if(!c.Oc){var g=I(c.path,{Sc:!0}).node;if(!g.oc.readdir)throw new E(D.dd);var h=g.oc.readdir(g);c.Oc=h}for(a=0;0<c.Oc.length&&a+268<=f;){var k=c.Oc.pop();if("."===k[0]){var m=1;var l=4}else{var q=zb(c.node,k);m=q.id;l=8192===(q.mode&61440)?2:16384===(q.mode&61440)?4:40960===(q.mode&61440)?10:8}w[d+a>>2]=m;w[d+a+4>>2]=c.position;Ca[d+a+8>>1]=268;A[d+a+10>>0]=l;wa(k,z,d+a+11,256);a+=268}return a}catch(v){return"undefined"!==
typeof FS&&v instanceof E||r(v),-v.vc}},v:function(a,b){L=b;try{var c=N();switch(M()){case 0:var d=M();return 0>d?-D.uc:Xb(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=M(),c.flags|=d,0;case 12:case 12:return d=M(),Ca[d+0>>1]=2,0;case 13:case 14:case 13:case 14:return 0;case 16:case 8:return-D.uc;case 9:return jb(D.uc),-1;default:return-D.uc}}catch(f){return"undefined"!==typeof FS&&f instanceof E||r(f),-f.vc}},R:function(a,b){L=b;try{var c=ta(M()),d=M(),f=M();
return Xb(c,d,f).fd}catch(g){return"undefined"!==typeof FS&&g instanceof E||r(g),-g.vc}},Q:function(a,b){L=b;try{var c=N(),d=M();switch(d){case 21509:case 21505:return c.tty?0:-D.Mc;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-D.Mc;case 21519:if(!c.tty)return-D.Mc;var f=M();return w[f>>2]=0;case 21520:return c.tty?-D.uc:-D.Mc;case 21531:a=f=M();if(!c.pc.me)throw new E(D.Mc);return c.pc.me(c,d,a);case 21523:return c.tty?0:-D.Mc;case 21524:return c.tty?0:-D.Mc;default:r("bad ioctl syscall "+
d)}}catch(g){return"undefined"!==typeof FS&&g instanceof E||r(g),-g.vc}},x:function(a,b){L=b;try{var c=N();Zb(c);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof E||r(d),-d.vc}},qa:function(a,b){L=b;try{var c=M(),d=M(),f=kc[c];if(!f)return 0;if(d===f.ne){var g=G[f.fd],h=f.flags,k=new Uint8Array(z.subarray(c,c+d));g&&g.pc.rd&&g.pc.rd(g,k,0,d,h);kc[c]=null;f.ud&&V(f.oe)}return 0}catch(m){return"undefined"!==typeof FS&&m instanceof E||r(m),-m.vc}},G:function(){},P:function(a){var b=mc[a];
delete mc[a];var c=b.elements,d=c.length,f=c.map(function(a){return a.zd}).concat(c.map(function(a){return a.Gd})),g=b.Zc,h=b.Bc;O([a],f,function(a){c.forEach(function(b,c){var f=a[c],g=b.xd,h=b.yd,k=a[c+d],l=b.Fd,m=b.Hd;b.read=function(a){return f.fromWireType(g(h,a))};b.write=function(a,b){var c=[];l(m,a,k.toWireType(c,b));nc(c)}});return[{name:b.name,fromWireType:function(a){for(var b=Array(d),f=0;f<d;++f)b[f]=c[f].read(a);h(a);return b},toWireType:function(a,f){if(d!==f.length)throw new TypeError("Incorrect number of tuple elements for "+
b.name+": expected="+d+", actual="+f.length);for(var k=g(),l=0;l<d;++l)c[l].write(k,f[l]);null!==a&&a.push(h,k);return k},argPackAdvance:8,readValueFromPointer:oc,zc:h}]})},F:function(a){var b=xc[a];delete xc[a];var c=b.Zc,d=b.Bc,f=b.Ud,g=f.map(function(a){return a.zd}).concat(f.map(function(a){return a.Gd}));O([a],g,function(a){var g={};f.forEach(function(b,c){var d=a[c],h=b.xd,k=b.yd,l=a[c+f.length],m=b.Fd,Pc=b.Hd;g[b.he]={read:function(a){return d.fromWireType(h(k,a))},write:function(a,b){var c=
[];m(Pc,a,l.toWireType(c,b));nc(c)}}});return[{name:b.name,fromWireType:function(a){var b={},c;for(c in g)b[c]=g[c].read(a);d(a);return b},toWireType:function(a,b){for(var f in g)if(!(f in b))throw new TypeError("Missing field");var h=c();for(f in g)g[f].write(h,b[f]);null!==a&&a.push(d,h);return h},argPackAdvance:8,readValueFromPointer:oc,zc:d}]})},pa:function(a,b,c,d,f){var g=yc(c);b=Q(b);P(a,{name:b,fromWireType:function(a){return!!a},toWireType:function(a,b){return b?d:f},argPackAdvance:8,readValueFromPointer:function(a){if(1===
c)var d=A;else if(2===c)d=Ca;else if(4===c)d=w;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(d[a>>g])},zc:null})},q:function(a,b,c,d,f,g,h,k,m,l,q,v,K){q=Q(q);g=U(f,g);k&&(k=U(h,k));l&&(l=U(m,l));K=U(v,K);var H=sc(q);Hc(H,function(){Yc("Cannot construct "+q+" due to unbound types",[d])});O([a,b,c],d?[d]:[],function(b){b=b[0];if(d){var c=b.qc;var f=c.Tc}else f=S.prototype;b=tc(H,function(){if(Object.getPrototypeOf(this)!==h)throw new Ac("Use 'new' to construct "+
q);if(void 0===m.Nc)throw new Ac(q+" has no accessible constructor");var a=m.Nc[arguments.length];if(void 0===a)throw new Ac("Tried to invoke ctor of "+q+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(m.Nc).toString()+") parameters instead!");return a.apply(this,arguments)});var h=Object.create(f,{constructor:{value:b}});b.prototype=h;var m=new Ic(q,b,h,K,c,g,k,l);c=new T(q,m,!0,!1,!1);f=new T(q+"*",m,!1,!1,!1);var v=new T(q+" const*",m,!1,!0,!1);Fc[a]={pointerType:f,
fe:v};Uc(H,b);return[c,f,v]})},w:function(a,b,c,d,f,g){var h=Zc(b,c);f=U(d,f);O([],[a],function(a){a=a[0];var c="constructor "+a.name;void 0===a.qc.Nc&&(a.qc.Nc=[]);if(void 0!==a.qc.Nc[b-1])throw new Ac("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+a.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");a.qc.Nc[b-1]=function(){Yc("Cannot construct "+a.name+" due to unbound types",h)};O([],h,
function(d){a.qc.Nc[b-1]=function(){arguments.length!==b-1&&R(c+" called with "+arguments.length+" arguments, expected "+(b-1));var a=[],h=Array(b);h[0]=g;for(var k=1;k<b;++k)h[k]=d[k].toWireType(a,arguments[k-1]);h=f.apply(null,h);nc(a);return d[0].fromWireType(h)};return[]});return[]})},f:function(a,b,c,d,f,g,h,k){var m=Zc(c,d);b=Q(b);g=U(f,g);O([],[a],function(a){function d(){Yc("Cannot call "+f+" due to unbound types",m)}a=a[0];var f=a.name+"."+b;k&&a.qc.se.push(b);var l=a.qc.Tc,H=l[b];void 0===
H||void 0===H.xc&&H.className!==a.name&&H.ld===c-2?(d.ld=c-2,d.className=a.name,l[b]=d):(Gc(l,b,f),l[b].xc[c-2]=d);O([],m,function(d){d=ad(f,d,a,g,h);void 0===l[b].xc?(d.ld=c-2,l[b]=d):l[b].xc[c-2]=d;return[]});return[]})},na:function(a,b,c){a=Q(a);O([],[b],function(b){b=b[0];e[a]=b.fromWireType(c);return[]})},ma:function(a,b){b=Q(b);P(a,{name:b,fromWireType:function(a){var b=W[a].value;cd(a);return b},toWireType:function(a,b){return Nc(b)},argPackAdvance:8,readValueFromPointer:oc,zc:null})},s:function(a,
b,c,d){function f(){}c=yc(c);b=Q(b);f.values={};P(a,{name:b,constructor:f,fromWireType:function(a){return this.constructor.values[a]},toWireType:function(a,b){return b.value},argPackAdvance:8,readValueFromPointer:dd(b,c,d),zc:null});Hc(b,f)},r:function(a,b,c){var d=ed(a,"enum");b=Q(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:tc(d.name+"_"+b,function(){})}});a.values[c]=d;a[b]=d},O:function(a,b,c){c=yc(c);b=Q(b);P(a,{name:b,fromWireType:function(a){return a},
toWireType:function(a,b){if("number"!==typeof b&&"boolean"!==typeof b)throw new TypeError('Cannot convert "'+Lc(b)+'" to '+this.name);return b},argPackAdvance:8,readValueFromPointer:fd(b,c),zc:null})},l:function(a,b,c,d,f,g){var h=Zc(b,c);a=Q(a);f=U(d,f);Hc(a,function(){Yc("Cannot call "+a+" due to unbound types",h)},b-1);O([],h,function(c){c=[c[0],null].concat(c.slice(1));Uc(a,ad(a,c,null,f,g),b-1);return[]})},p:function(a,b,c,d,f){function g(a){return a}b=Q(b);-1===f&&(f=4294967295);var h=yc(c);
if(0===d){var k=32-8*c;g=function(a){return a<<k>>>k}}var m=-1!=b.indexOf("unsigned");P(a,{name:b,fromWireType:g,toWireType:function(a,c){if("number"!==typeof c&&"boolean"!==typeof c)throw new TypeError('Cannot convert "'+Lc(c)+'" to '+this.name);if(c<d||c>f)throw new TypeError('Passing a number "'+Lc(c)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return m?c>>>0:c|0},argPackAdvance:8,readValueFromPointer:gd(b,h,0!==d),zc:null})},
m:function(a,b,c){function d(a){a>>=2;var b=B;return new f(b.buffer,b[a+1],b[a])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=Q(c);P(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{le:!0})},u:function(a,b,c,d,f,g,h,k,m,l,q,v){c=Q(c);g=U(f,g);k=U(h,k);l=U(m,l);v=U(q,v);O([a],[b],function(a){a=a[0];return[new T(c,a.qc,!1,!1,!0,a,d,g,k,l,v)]})},N:function(a,b){b=Q(b);var c="std::string"===b;P(a,{name:b,fromWireType:function(a){var b=
B[a>>2];if(c){var d=z[a+4+b],h=0;0!=d&&(h=d,z[a+4+b]=0);var k=a+4;for(d=0;d<=b;++d){var m=a+4+d;if(0==z[m]){k=ua(z,k);if(void 0===l)var l=k;else l+=String.fromCharCode(0),l+=k;k=m+1}}0!=h&&(z[a+4+b]=h)}else{l=Array(b);for(d=0;d<b;++d)l[d]=String.fromCharCode(z[a+4+d]);l=l.join("")}V(a);return l},toWireType:function(a,b){b instanceof ArrayBuffer&&(b=new Uint8Array(b));var d="string"===typeof b;d||b instanceof Uint8Array||b instanceof Uint8ClampedArray||b instanceof Int8Array||R("Cannot pass non-string to std::string");
var f=(c&&d?function(){return xa(b)}:function(){return b.length})(),k=gb(4+f+1);B[k>>2]=f;if(c&&d)wa(b,z,k+4,f+1);else if(d)for(d=0;d<f;++d){var m=b.charCodeAt(d);255<m&&(V(k),R("String has UTF-16 code units that do not fit in 8 bits"));z[k+4+d]=m}else for(d=0;d<f;++d)z[k+4+d]=b[d];null!==a&&a.push(V,k);return k},argPackAdvance:8,readValueFromPointer:oc,zc:function(a){V(a)}})},la:function(a,b,c){c=Q(c);if(2===b){var d=function(){return Da};var f=1}else 4===b&&(d=function(){return B},f=2);P(a,{name:c,
fromWireType:function(a){for(var b=d(),c=B[a>>2],g=Array(c),l=a+4>>f,q=0;q<c;++q)g[q]=String.fromCharCode(b[l+q]);V(a);return g.join("")},toWireType:function(a,c){var g=d(),h=c.length,l=gb(4+h*b);B[l>>2]=h;for(var q=l+4>>f,v=0;v<h;++v)g[q+v]=c.charCodeAt(v);null!==a&&a.push(V,l);return l},argPackAdvance:8,readValueFromPointer:oc,zc:function(a){V(a)}})},M:function(a,b,c,d,f,g){mc[a]={name:Q(b),Zc:U(c,d),Bc:U(f,g),elements:[]}},L:function(a,b,c,d,f,g,h,k,m){mc[a].elements.push({zd:b,xd:U(c,d),yd:f,
Gd:g,Fd:U(h,k),Hd:m})},E:function(a,b,c,d,f,g){xc[a]={name:Q(b),Zc:U(c,d),Bc:U(f,g),Ud:[]}},D:function(a,b,c,d,f,g,h,k,m,l){xc[a].Ud.push({he:Q(b),zd:c,xd:U(d,f),yd:g,Gd:h,Fd:U(k,m),Hd:l})},ka:function(a,b){b=Q(b);P(a,{Bg:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},C:cd,ja:function(a){4<a&&(W[a].Uc+=1)},ia:function(a){var b=hd[a];return Nc(void 0===b?Q(a):b)},K:function(a,b){a=ed(a,"_emval_take_value");a=a.readValueFromPointer(b);return Nc(a)},e:function(){e.abort()},
B:function(a){if(X[a]){var b=X[a];0==--b.Uc&&(b.module.ee&&b.module.ee.forEach(function(a){a()}),delete id[b.name],delete X[a]);return 0}return 1},A:function(a,b){r("To use dlopen, you need to use Emscripten's linking support, see https://github.com/kripken/emscripten/wiki/Linking");var c=[];if(0===a)a="__self__";else{a=ta(a);var d=function(a){return(a=fc(a))&&!a.Bd&&!a.Ad};if(!d(a)){C.LD_LIBRARY_PATH&&(c=C.LD_LIBRARY_PATH.split(":"));for(var f in c){var g=lb(c[f]+"/"+a);if(d(g)){a=g;break}}}}if(id[a]){var h=
id[a];X[h].Uc++;return h}if("__self__"===a){h=-1;var k=e}else{if(void 0!==e.preloadedWasm&&void 0!==e.preloadedWasm[a])k=e.preloadedWasm[a];else{c=fc(a);if(!c||c.Bd||c.Ad)return 0;jc(c);try{h=bc(a),h instanceof Uint8Array||(h=new Uint8Array(h)),k=loadWebAssemblyModule(h)}catch(l){return 0}}h=1;for(var m in X)X.hasOwnProperty(m)&&h++;if(b&256)for(f in k)k.hasOwnProperty(f)&&"_"==f[0]&&(e[f]=k[f])}X[h]={Uc:1,name:a,module:k};return id[a]=h},z:function(a,b){b=ta(b);if(X[a]&&(a=X[a],b="_"+b,a.module.hasOwnProperty(b))){b=
a.module[b];if("function"===typeof b)a:{for(a=0;0>a;a++)if(!ra[a]){ra[a]=b;b=1+a;break a}throw"Finished up all reserved function pointers. Use a higher value for RESERVED_FUNCTION_POINTERS.";}return b}return 0},ha:function(a,b){jd(a,b)},ga:function(a,b,c){z.set(z.subarray(b,b+c),a);return a},fa:function(a){if(!e.noExitRuntime&&(sa=!0,Ka=sd,Qa(Ua),e.onExit))e.onExit(a);e.quit(a,new ka(a))},ea:kd,da:function(a){return Math.log(a)/Math.LN2},ca:function(){r("trap!")},t:Ya,c:jd,ba:function(a){return ld[a]||
0},aa:function(a){if(0==a)return D.uc;w[a>>2]=md;ld[md]=0;md++;return 0},$:nd,_:function(a,b){if(!(a in ld))return D.uc;ld[a]=b;return 0},Z:function(){},J:function(){},Y:function(){},I:function(){},a:x,b:Ka};var td=e.asm(e.be,e.ce,buffer);e.asm=td;var db=e.__GLOBAL__sub_I_bind_cpp=function(){return e.asm.Fa.apply(null,arguments)},cb=e.__GLOBAL__sub_I_canvaskit_bindings_cpp=function(){return e.asm.Ga.apply(null,arguments)};
e.__Z11ApplyPathOpR6SkPathRKS_8SkPathOp=function(){return e.asm.Ha.apply(null,arguments)};e.__Z11ToSVGStringRK6SkPath=function(){return e.asm.Ia.apply(null,arguments)};e.__Z13ApplySimplifyR6SkPath=function(){return e.asm.Ja.apply(null,arguments)};e.__Z14MakePathFromOpRK6SkPathS1_8SkPathOp=function(){return e.asm.Ka.apply(null,arguments)};e.__Z6EqualsRK6SkPathS1_=function(){return e.asm.La.apply(null,arguments)};e.__Z8CopyPathRK6SkPath=function(){return e.asm.Ma.apply(null,arguments)};
e.__Z9initFontsv=function(){return e.asm.Na.apply(null,arguments)};var eb=e.___emscripten_environ_constructor=function(){return e.asm.Oa.apply(null,arguments)};e.___errno_location=function(){return e.asm.Pa.apply(null,arguments)};
var Xc=e.___getTypeName=function(){return e.asm.Qa.apply(null,arguments)},Na=e._emscripten_replace_memory=function(){return e.asm._emscripten_replace_memory.apply(null,arguments)},V=e._free=function(){return e.asm.Ra.apply(null,arguments)},gb=e._malloc=function(){return e.asm.Sa.apply(null,arguments)},qd=e._memalign=function(){return e.asm.Ta.apply(null,arguments)},rd=e._memset=function(){return e.asm.Ua.apply(null,arguments)};e.setThrew=function(){return e.asm.jc.apply(null,arguments)};
var Z=e.stackRestore=function(){return e.asm.kc.apply(null,arguments)},Y=e.stackSave=function(){return e.asm.lc.apply(null,arguments)};e.dynCall_fiff=function(){return e.asm.Va.apply(null,arguments)};e.dynCall_fii=function(){return e.asm.Wa.apply(null,arguments)};e.dynCall_fiii=function(){return e.asm.Xa.apply(null,arguments)};e.dynCall_i=function(){return e.asm.Ya.apply(null,arguments)};e.dynCall_ii=function(){return e.asm.Za.apply(null,arguments)};
e.dynCall_iidi=function(){return e.asm._a.apply(null,arguments)};e.dynCall_iif=function(){return e.asm.$a.apply(null,arguments)};e.dynCall_iifff=function(){return e.asm.ab.apply(null,arguments)};e.dynCall_iiffi=function(){return e.asm.bb.apply(null,arguments)};e.dynCall_iii=function(){return e.asm.cb.apply(null,arguments)};e.dynCall_iiifff=function(){return e.asm.db.apply(null,arguments)};e.dynCall_iiiffi=function(){return e.asm.eb.apply(null,arguments)};
e.dynCall_iiifiiiii=function(){return e.asm.fb.apply(null,arguments)};e.dynCall_iiifiiiiii=function(){return e.asm.gb.apply(null,arguments)};e.dynCall_iiii=function(){return e.asm.hb.apply(null,arguments)};e.dynCall_iiiif=function(){return e.asm.ib.apply(null,arguments)};e.dynCall_iiiii=function(){return e.asm.jb.apply(null,arguments)};e.dynCall_iiiiii=function(){return e.asm.kb.apply(null,arguments)};e.dynCall_iiiiiii=function(){return e.asm.lb.apply(null,arguments)};
e.dynCall_iiiiiiii=function(){return e.asm.mb.apply(null,arguments)};e.dynCall_iiiiiiiii=function(){return e.asm.nb.apply(null,arguments)};e.dynCall_iiiiiiiiii=function(){return e.asm.ob.apply(null,arguments)};e.dynCall_iiiiiiiiiii=function(){return e.asm.pb.apply(null,arguments)};e.dynCall_jiiiijiiiii=function(){return e.asm.qb.apply(null,arguments)};e.dynCall_v=function(){return e.asm.rb.apply(null,arguments)};e.dynCall_vi=function(){return e.asm.sb.apply(null,arguments)};
e.dynCall_viddi=function(){return e.asm.tb.apply(null,arguments)};e.dynCall_vif=function(){return e.asm.ub.apply(null,arguments)};e.dynCall_viff=function(){return e.asm.vb.apply(null,arguments)};e.dynCall_vifff=function(){return e.asm.wb.apply(null,arguments)};e.dynCall_viffff=function(){return e.asm.xb.apply(null,arguments)};e.dynCall_vifffff=function(){return e.asm.yb.apply(null,arguments)};e.dynCall_viffffff=function(){return e.asm.zb.apply(null,arguments)};
e.dynCall_vifffffffff=function(){return e.asm.Ab.apply(null,arguments)};e.dynCall_vifffffi=function(){return e.asm.Bb.apply(null,arguments)};e.dynCall_viffi=function(){return e.asm.Cb.apply(null,arguments)};e.dynCall_vifii=function(){return e.asm.Db.apply(null,arguments)};e.dynCall_vii=function(){return e.asm.Eb.apply(null,arguments)};e.dynCall_viid=function(){return e.asm.Fb.apply(null,arguments)};e.dynCall_viif=function(){return e.asm.Gb.apply(null,arguments)};
e.dynCall_viifd=function(){return e.asm.Hb.apply(null,arguments)};e.dynCall_viiff=function(){return e.asm.Ib.apply(null,arguments)};e.dynCall_viifff=function(){return e.asm.Jb.apply(null,arguments)};e.dynCall_viiffff=function(){return e.asm.Kb.apply(null,arguments)};e.dynCall_viifffff=function(){return e.asm.Lb.apply(null,arguments)};e.dynCall_viiffffff=function(){return e.asm.Mb.apply(null,arguments)};e.dynCall_viifffffffff=function(){return e.asm.Nb.apply(null,arguments)};
e.dynCall_viifffffi=function(){return e.asm.Ob.apply(null,arguments)};e.dynCall_viiffi=function(){return e.asm.Pb.apply(null,arguments)};e.dynCall_viiffii=function(){return e.asm.Qb.apply(null,arguments)};e.dynCall_viifi=function(){return e.asm.Rb.apply(null,arguments)};e.dynCall_viifiiiii=function(){return e.asm.Sb.apply(null,arguments)};e.dynCall_viifiiiiii=function(){return e.asm.Tb.apply(null,arguments)};e.dynCall_viii=function(){return e.asm.Ub.apply(null,arguments)};
e.dynCall_viiif=function(){return e.asm.Vb.apply(null,arguments)};e.dynCall_viiifffffffff=function(){return e.asm.Wb.apply(null,arguments)};e.dynCall_viiiffi=function(){return e.asm.Xb.apply(null,arguments)};e.dynCall_viiifii=function(){return e.asm.Yb.apply(null,arguments)};e.dynCall_viiii=function(){return e.asm.Zb.apply(null,arguments)};e.dynCall_viiiifi=function(){return e.asm._b.apply(null,arguments)};e.dynCall_viiiii=function(){return e.asm.$b.apply(null,arguments)};
e.dynCall_viiiiiffii=function(){return e.asm.ac.apply(null,arguments)};e.dynCall_viiiiii=function(){return e.asm.bc.apply(null,arguments)};e.dynCall_viiiiiii=function(){return e.asm.cc.apply(null,arguments)};e.dynCall_viiiiiiii=function(){return e.asm.dc.apply(null,arguments)};e.dynCall_viiiiiiiii=function(){return e.asm.ec.apply(null,arguments)};e.dynCall_viiiiiiiiii=function(){return e.asm.fc.apply(null,arguments)};e.dynCall_viiiiiiiiiiiiiii=function(){return e.asm.gc.apply(null,arguments)};
e.dynCall_viiiiij=function(){return e.asm.hc.apply(null,arguments)};e.dynCall_viiij=function(){return e.asm.ic.apply(null,arguments)};e.asm=td;e.then=function(a){if(e.calledRun)a(e);else{var b=e.onRuntimeInitialized;e.onRuntimeInitialized=function(){b&&b();a(e)}}return e};function ka(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ka.prototype=Error();ka.prototype.constructor=ka;var sd;ab=function ud(){e.calledRun||vd();e.calledRun||(ab=ud)};
function vd(){function a(){if(!e.calledRun&&(e.calledRun=!0,!sa)){Wa||(Wa=!0,Qa(Sa));Qa(Ta);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var a=e.postRun.shift();Va.unshift(a)}Qa(Va)}}if(!(0<Za)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Xa();Qa(Ra);0<Za||e.calledRun||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},
1);a()},1)):a())}}e.run=vd;function r(a){if(e.onAbort)e.onAbort(a);void 0!==a?(la(a),t(a),a=JSON.stringify(a)):a="";sa=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}e.abort=r;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();e.noExitRuntime=!0;vd();


  return CanvasKitInit;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
    module.exports = CanvasKitInit;
  else if (typeof define === 'function' && define['amd'])
    define([], function() { return CanvasKitInit; });
  else if (typeof exports === 'object')
    exports["CanvasKitInit"] = CanvasKitInit;
  